[package]
name = "gui-app-browser"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
hex = { workspace = true }
log = { workspace = true }
log-server = { workspace = true }
quantum-link = { workspace = true }
ql-utils = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
server = { workspace = true }
slint-keyos-platform = { path = "../../slint-keyos-platform/runtime" }

[build-dependencies]
slint-keyos-platform-build = { path = "../../slint-keyos-platform/build" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(keyos)'] }
